spring: 
  datasource:
    url: jdbc:postgresql://localhost:5432/ProjetoFono
    username: postgres
    password: postgres
    hikari:
        maximum-pool-size: 4
        connection-test-query: SELECT 1

jpa:        
    database: POSTGRESQL
    show-sql: true
    properties:
        hibernate:
            temp.use_jdbc_metadata_defaults: false
    
app:
    dataStore: /tmp/
    
jsf:
  PROJECT_STAGE: Development
  FACELETS_LIBRARIES: /tags/tags.taglib.xml
  primefaces:
    theme: cupertino
    moveScriptsToBottom: true
joinfaces:
  version: @project.parent.version@
spring-boot:
  version: @project.parent.parent.version@
tomcat:
  version: @tomcat.version@
cdi:
  version: @cdi.version@
mojarra:
  version: @mojarra.version@
omnifaces:
  version: @omnifaces.version@
primefaces:
  version: @primefaces.version@
primefaces-extensions:
  version: @primefaces-extensions.version@
